version: '3.8'

networks:
  net:
    driver: bridge

services:

  db:
    container_name: db
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=pyIntro
      - MYSQL_USER=zahar
      - MYSQL_PASSWORD=1230321!
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3307:3306"
    networks:
      - net
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 5s
      timeout: 5s
      retries: 10

  applications:
    container_name: app
    build:
        dockerfile: Dockerfile
        context: .
    env_file:
      - .env
    ports:
      - "80:80"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - net