version: '3.8'

services:

  db:
    container_name: db
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=pyIntro
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 5s
      timeout: 5s
      retries: 10

  applications:
    container_name: app
    build:
        dockerfile: Dockerfile
        context: .
    env_file:
      - .env
    ports:
      - "80:80"
    volumes:
      - ./:/python-super-introduction
    depends_on:
      db:
        condition: service_healthy